name: Production Build
on:
  push:
    tags:
      - "v*.*.*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Build
        run: yarn prod

      - name: Zip Folder
        run: zip -r ./kaiak.zip

      - name: Release Drafter
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        with:
          name: ${{ steps.package-version.outputs.current-version }}
          tag: v${{ steps.package-version.outputs.current-version }}
          version: ${{ steps.package-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_drafter.outputs.upload_url }} # This pulls ID from the Release Drafter step
          asset_path: ./kaiak.zip
          asset_name: kaiak.zip
          asset_content_type: application/zip
